const LightColors = {
  APP_PRIMARY: '#6F44A3',
  APP_SECONDARY: '#33AAEB',

  APP_STATUS_BAR_COLOR: '#299676',
  APP_BACKGROUND_COLOR: '#FFFFFF',
  APP_SCREEN_BACKGROUND_COLOR: '#EAEAEA',

  APP_ACTIVITY_INDICATOR_COLOR: '#6F44A3',

  INPUT: {
    SHADOW_COLOR: '#000000',
    BORDER_COLOR: '#000000',
    TEXT_COLOR: '#000000',
    TEXT_PLACE_HOLDER_COLOR: '#B1BDC8',
    BACKGROUND_COLOR: '#FFFFFF',
  },

  TEXT: {
    PRIMARY: '#000000',
    SECONDARY: '#6740B4',
  },
};

export default LightColors;
