export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';

export const SET_APP_STATE = 'SET_APP_STATE';

export const USER_PASSWORD_VERIFICATION = 'USER_PASSWORD_VERIFICATION';
export const USER_PASSWORD_VERIFICATION_SUCCESS =
  'USER_PASSWORD_VERIFICATION_SUCCESS';
export const USER_PASSWORD_VERIFICATION_ERROR =
  'USER_PASSWORD_VERIFICATION_ERROR';
export const USER_PASSWORD_VERIFICATION_FOR_ROSTER =
  'USER_PASSWORD_VERIFICATION_FOR_ROSTER';
export const USER_PASSWORD_VERIFICATION_FOR_ROSTER_SUCCESS =
  'USER_PASSWORD_VERIFICATION_FOR_ROSTER_SUCCESS';
export const USER_PASSWORD_VERIFICATION_FOR_ROSTER_ERROR =
  'USER_PASSWORD_VERIFICATION_FOR_ROSTER_ERROR';
export const SET_OTP_VERIFICATION = 'SET_OTP_VERIFICATION';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_USER_WORKFLOW = 'SET_USER_WORKFLOW';
export const SET_COMPANY_NAME = 'SET_COMPANY_NAME';
export const SET_VES_STATUS = 'SET_VES_STATUS';
export const SET_VES_STATUS_ERROR = 'SET_VES_STATUS_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const LOADING = 'LOADING';
export const GET_USER_IDENTITY = 'GET_USER_IDENTITY';
export const GET_USER_IDENTITY_SUCCESS = 'GET_USER_IDENTITY_SUCCESS';
export const GET_USER_IDENTITY_ERROR = 'GET_USER_IDENTITY_ERROR';
export const GET_USER_IDENTITY_ERROR_WITH_DATA =
  'GET_USER_IDENTITY_ERROR_WITH_DATA';
export const RESET_SCANNED_STATE = 'RESET_SCANNED_STATE';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR';
export const GET_USER_PROFILES = 'GET_USER_PROFILES';
export const GET_USER_PROFILES_SUCCESS = 'GET_USER_PROFILES_SUCCESS';
export const GET_USER_PROFILES_ERROR = 'GET_USER_PROFILES_ERROR';
export const CHECKOUT_USER = 'CHECKOUT_USER';
export const CHECKOUT_USER_SUCCESS = 'CHECKOUT_USER_SUCCESS';
export const CHECKOUT_USER_ERROR = 'CHECKOUT_USER_ERROR';
export const CHECKIN_USER = 'CHECKIN_USER';
export const CHECKIN_USER_SUCCESS = 'CHECKIN_USER_SUCCESS';
export const CHECKIN_USER_ERROR = 'CHECKIN_USER_ERROR';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const SET_PURPOSE = 'SET_PURPOSE';
export const SET_REASON = 'SET_REASON';
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_ROOMS_ERROR = 'GET_ALL_ROOMS_ERROR';
export const GET_ALL_REASONS = 'GET_ALL_REASONS';
export const GET_ALL_REASONS_SUCCESS = 'GET_ALL_REASONS_SUCCESS';
export const GET_ALL_REASONS_ERROR = 'GET_ALL_REASONS_ERROR';

export const GET_COVID_ANSWERS = 'GET_COVID_ANSWERS';
export const GET_COVID_ANSWERS_SUCCESS = 'GET_COVID_ANSWERS_SUCCESS';
export const GET_COVID_ANSWERS_ERROR = 'GET_COVID_ANSWERS_ERROR';

export const POST_COVID_ANSWERS = 'POST_COVID_ANSWERS';
export const POST_COVID_ANSWERS_SUCCESS = 'POST_COVID_ANSWERS_SUCCESS';
export const POST_COVID_ANSWERS_ERROR = 'POST_COVID_ANSWERS_ERROR';

export const GET_ALL_REASONS_LEVEL_2 = 'GET_ALL_REASONS_LEVEL_2';
export const GET_ALL_REASONS_SUCCESS_LEVEL_2 =
  'GET_ALL_REASONS_SUCCESS_LEVEL_2';
export const GET_ALL_REASONS_ERROR_LEVEL_2 = 'GET_ALL_REASONS_ERROR_LEVEL_2';
export const NETWORK_STATE = 'NETWORK_STATE';
export const USER_AFFILIATION = 'USER_AFFILIATION';
export const USER_AFFILIATION_SUCCESS = 'USER_AFFILIATION_SUCCESS';
export const USER_AFFILIATION_ERROR = 'USER_AFFILIATION_ERROR';
export const SET_USER_AFFILIATION = 'SET_USER_AFFILIATION';
export const USER_PERMISSION_CLEAR = 'USER_PERMISSION_CLEAR';
export const USER_PERMISSION_IDLE = 'USER_PERMISSION_IDLE';
export const USER_PERMISSION_FETCHING = 'USER_PERMISSION_FETCHING';
export const USER_PERMISSION_SUCCESS = 'USER_PERMISSION_SUCCESS';
export const USER_PERMISSION_NULL_SUCCESS = 'USER_PERMISSION_NULL_SUCCESS';
export const USER_PERMISSION_ERROR = 'USER_PERMISSION_ERROR';
export const SET_LOGIN_AFFILIATIONS = 'SET_LOGIN_AFFILIATIONS';
export const SELECT_USERTYPE = 'SELECT_USERTYPE';
export const ALLOWED_USER_TYPES_IDLE = 'ALLOWED_USER_TYPES_IDLE';
export const ALLOWED_USER_TYPES = 'ALLOWED_USER_TYPES';
export const ALLOWED_USER_TYPES_SUCCESS = 'ALLOWED_USER_TYPES_SUCCESS';
export const ALLOWED_USER_TYPES_NULL_SUCCESS =
  'ALLOWED_USER_TYPES_NULL_SUCCESS';
export const ALLOWED_USER_TYPES_ERROR = 'ALLOWED_USER_TYPES_ERROR';
export const SET_ALLOWED_USER_TYPES = 'SET_ALLOWED_USER_TYPES';

export const ALL_GLOBAL_SETTINGS = 'ALL_GLOBAL_SETTINGS';
export const ALL_GLOBAL_SETTINGS_SUCCESS = 'ALL_GLOBAL_SETTINGS_SUCCESS';
export const ALL_GLOBAL_SETTINGS_NULL_SUCCESS =
  'ALL_GLOBAL_SETTINGS_NULL_SUCCESS';
export const ALL_GLOBAL_SETTINGS_ERROR = 'ALL_GLOBAL_SETTINGS_ERROR';

export const GET_USER_TWO_FACTOR_INFO = 'GET_USER_TWO_FACTOR_INFO';
export const GET_USER_TWO_FACTOR_INFO_SUCCESS =
  'GET_USER_TWO_FACTOR_INFO_SUCCESS';
export const GET_USER_TWO_FACTOR_INFO_NULL_SUCCESS =
  'GET_USER_TWO_FACTOR_INFO_NULL_SUCCESS';
export const GET_USER_TWO_FACTOR_INFO_ERROR = 'GET_USER_TWO_FACTOR_INFO_ERROR';

export const RESEND_OTP = 'RESEND_OTP';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_ERROR = 'RESEND_OTP_ERROR';

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';

export const SET_SOUND_BEGIN = 'SET_SOUND_BEGIN';
export const SET_SOUND_SUCCESS = 'SET_SOUND_SUCCESS';

export const ALL_ATTENDANCE_GLOBAL_SETTINGS = 'ALL_ATTENDANCE_GLOBAL_SETTINGS';
export const ALL_ATTENDANCE_GLOBAL_SETTINGS_SUCCESS =
  'ALL_ATTENDANCE_GLOBAL_SETTINGS_SUCCESS';
export const ALL_ATTENDANCE_GLOBAL_SETTINGS_NULL_SUCCESS =
  'ALL_ATTENDANCE_GLOBAL_SETTINGS_NULL_SUCCESS';
export const ALL_ATTENDANCE_GLOBAL_SETTINGS_ERROR =
  'ALL_ATTENDANCE_GLOBAL_SETTINGS_ERROR';

export const GET_COVID_QUESTION_FLAG = 'GET_COVID_QUESTION_FLAG';
export const GET_COVID_QUESTION_FLAG_SUCCESS =
  'GET_COVID_QUESTION_FLAG_SUCCESS';
export const GET_COVID_QUESTION_FLAG_ERROR = 'GET_COVID_QUESTION_FLAG_ERROR';

export const GET_REUNIFICATION_REASONS = 'GET_REUNIFICATION_REASONS';
export const GET_REUNIFICATION_REASONS_SUCCESS =
  'GET_REUNIFICATION_REASONS_SUCCESS';
export const GET_REUNIFICATION_REASONS_ERROR =
  'GET_REUNIFICATION_REASONS_ERROR';

export const GET_COVID_LOOKUPS = 'GET_COVID_LOOKUPS';
export const GET_COVID_LOOKUPS_SUCCESS = 'GET_COVID_LOOKUPS_SUCCESS';
export const GET_COVID_LOOKUPS_ERROR = 'GET_COVID_LOOKUPS_ERROR';

export const GET_WORK_COMP_LOOKUPS = 'GET_WORK_COMP_LOOKUPS';
export const GET_WORK_COMP_LOOKUPS_SUCCESS = 'GET_WORK_COMP_LOOKUPS_SUCCESS';
export const GET_WORK_COMP_LOOKUPS_ERROR = 'GET_WORK_COMP_LOOKUPS_ERROR';

export const GET_SCHEDULES = 'GET_SCHEDULES';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_ERROR = 'GET_SCHEDULES_ERROR';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const UPDATE_CLASS_ERROR = 'UPDATE_CLASS_ERROR';
export const TIMER_END_CLASS = 'TIMER_END_CLASS';
export const TIMER_END_CLASS_SUCCESS = 'TIMER_END_CLASS_SUCCESS';
export const TIMER_END_CLASS_ERROR = 'TIMER_END_CLASS_ERROR';
export const GET_STUDENT_IDENTITY = 'GET_STUDENT_IDENTITY';
export const GET_STUDENT_IDENTITY_SUCCESS = 'GET_STUDENT_IDENTITY_SUCCESS';
export const GET_STUDENT_IDENTITY_ERROR = 'GET_STUDENT_IDENTITY_ERROR';
export const RESET_SEARCH_STUDENT = 'RESET_SEARCH_STUDENT';
export const RESET_CLASS_DETAIL = 'RESET_CLASS_DETAIL';
export const AUTO_CHECKIN_BEGIN = 'AUTO_CHECKIN_BEGIN';
export const AUTO_CHECKIN_SUCCESS = 'AUTO_CHECKIN_SUCCESS';
export const AUTO_CHECKIN_ERROR = 'AUTO_CHECKIN_ERROR';

export const AUTO_CHECKIN_V2_BEGIN = 'AUTO_CHECKIN_V2_BEGIN';
export const AUTO_CHECKIN_V2_SUCCESS = 'AUTO_CHECKIN_V2_SUCCESS';
export const AUTO_CHECKIN_V2_ERROR = 'AUTO_CHECKIN_V2_ERROR';

export const VIEW_ROSTER_BEGIN = 'VIEW_ROSTER_BEGIN';
export const VIEW_ROSTER_SUCCESS = 'VIEW_ROSTER_SUCCESS';
export const VIEW_ROSTER_ERROR = 'VIEW_ROSTER_ERROR';
export const GET_STUDENTS_STATUS_BEGIN = 'GET_STUDENTS_STATUS_BEGIN';
export const GET_STUDENTS_STATUS_SUCCESS = 'GET_STUDENTS_STATUS_SUCCESS';
export const GET_STUDENTS_STATUS_ERROR = 'GET_STUDENTS_STATUS_ERROR';
export const UPDATE_VIEW_ROSTER = 'UPDATE_VIEW_ROSTER';
export const SUBMIT_STUDENT_STATUS_BEGIN = 'SUBMIT_STUDENT_STATUS_BEGIN';
export const SUBMIT_STUDENT_STATUS_SUCCESS = 'SUBMIT_STUDENT_STATUS_SUCCESS';
export const SUBMIT_STUDENT_STATUS_ERROR = 'SUBMIT_STUDENT_STATUS_ERROR';
export const SET_ALL_STUDENT_PRESENT_BEGIN = 'SET_ALL_STUDENT_PRESENT_BEGIN';
export const SET_ALL_STUDENT_PRESENT_SUCCESS =
  'SET_ALL_STUDENT_PRESENT_SUCCESS';
export const SET_ALL_STUDENT_PRESENT_ERROR = 'SET_ALL_STUDENT_PRESENT_ERROR';
export const SET_CURRENT_PENDING_CLASS = 'SET_CURRENT_PENDING_CLASS';

export const GET_CONTRACTOR_VALIDATION_BEGIN =
  'GET_CONTRACTOR_VALIDATION_BEGIN';
export const GET_CONTRACTOR_VALIDATION_SUCCESS =
  'GET_CONTRACTOR_VALIDATION_SUCCESS';
export const GET_CONTRACTOR_VALIDATION_ERROR =
  'GET_CONTRACTOR_VALIDATION_ERROR';

export const GET_CONTRACTOR_COMPANIES_BEGIN = 'GET_CONTRACTOR_COMPANIES_BEGIN';
export const GET_CONTRACTOR_COMPANIES_SUCCESS =
  'GET_CONTRACTOR_COMPANIES_SUCCESS';
export const GET_CONTRACTOR_COMPANIES_ERROR = 'GET_CONTRACTOR_COMPANIES_ERROR';

export const FETCH_SUB_TENANTS_BEGIN = 'FETCH_SUB_TENANTS_BEGIN';
export const FETCH_SUB_TENANTS_SUCCESS = 'FETCH_SUB_TENANTS_SUCCESS';
export const FETCH_SUB_TENANTS_ERROR = 'FETCH_SUB_TENANTS_ERROR';
export const SET_SUB_TENANT_SELECTION = 'SET_SUB_TENANT_SELECTION';

export const GET_VISIT_INFO = 'GET_VISIT_INFO';
export const GET_VISIT_INFO_SUCCESS = 'GET_VISIT_INFO_SUCCESS';
export const GET_VISIT_INFO_SUCCESS_BUT_NULL =
  'GET_VISIT_INFO_SUCCESS_BUT_NULL';
export const GET_VISIT_INFO_ERROR = 'GET_VISIT_INFO_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SET_CONTRACTOR_COMPANY_ID = 'SET_CONTRACTOR_COMPANY_ID';

export const SET_DEVICE_ORIENTATION = 'SET_DEVICE_ORIENTATION';
export const SET_DEVICE_WIDTH_HEIGHT_VALUES = 'SET_DEVICE_WIDTH_HEIGHT_VALUES';
export const RESET_APP = 'RESET_APP';

export const GET_TRAILER_TYPE_LOOKUPS = 'GET_TRAILER_TYPE_LOOKUPS';
export const GET_TRAILER_TYPE_LOOKUPS_SUCCESS =
  'GET_TRAILER_TYPE_LOOKUPS_SUCCESS';
export const GET_TRAILER_TYPE_LOOKUPS_ERROR = 'GET_TRAILER_TYPE_LOOKUPS_ERROR';

export const GET_USER_CREDENTIALS = 'GET_USER_CREDENTIALS';
export const GET_USER_CREDENTIALS_SUCCESS = 'GET_USER_CREDENTIALS_SUCCESS';
export const GET_USER_CREDENTIALS_ERROR = 'GET_USER_CREDENTIALS_ERROR';

export const GET_CONTRACTING_COMPANIES = 'GET_CONTRACTING_COMPANIES';
export const GET_CONTRACTING_COMPANIES_SUCCESS =
  'GET_CONTRACTING_COMPANIES_SUCCESS';
export const GET_CONTRACTING_COMPANIES_ERROR =
  'GET_CONTRACTING_COMPANIES_ERROR';

export const VALIDATE_LOAD_AND_GET_USER_IDLE =
  'VALIDATE_LOAD_AND_GET_USER_IDLE';
export const VALIDATE_LOAD_AND_GET_USER = 'VALIDATE_LOAD_AND_GET_USER';
export const VALIDATE_LOAD_AND_GET_USER_SUCCESS =
  'VALIDATE_LOAD_AND_GET_USER_SUCCESS';
export const VALIDATE_LOAD_AND_GET_USER_ERROR =
  'VALIDATE_LOAD_AND_GET_USER_ERROR';

export const DOCK_USER_CHECKIN_IDLE = 'DOCK_USER_CHECKIN_IDLE';
export const DOCK_USER_CHECKIN = 'DOCK_USER_CHECKIN';
export const DOCK_USER_CHECKIN_SUCCESS = 'DOCK_USER_CHECKIN_SUCCESS';
export const DOCK_USER_CHECKIN_ERROR = 'DOCK_USER_CHECKIN_ERROR';

export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
export const UPDATE_CREDENTIALS_SUCCESS = 'UPDATE_CREDENTIALS_SUCCESS';
export const UPDATE_CREDENTIALS_ERROR = 'UPDATE_CREDENTIALS_ERROR';

export const DOCK_GENERATE_OTP = 'DOCK_GENERATE_OTP';
export const DOCK_GENERATE_OTP_SUCCESS = 'DOCK_GENERATE_OTP_SUCCESS';
export const DOCK_GENERATE_OTP_ERROR = 'DOCK_GENERATE_OTP_ERROR';

export const DOCK_VERIFY_OTP = 'DOCK_VERIFY_OTP';
export const DOCK_VERIFY_OTP_SUCCESS = 'DOCK_VERIFY_OTP_SUCCESS';
export const DOCK_VERIFY_OTP_ERROR = 'DOCK_VERIFY_OTP_ERROR';
export const RESET_OTP_STATE = 'RESET_OTP_STATE';

export const SET_TRIP_DATA = 'SET_TRIP_DATA';

export const GET_ORG_LOGO_PENDING = 'GET_ORG_LOGO_PENDING';
export const GET_ORG_LOGO_SUCCESS = 'GET_ORG_LOGO_SUCCESS';
export const GET_ORG_LOGO_ERROR = 'GET_ORG_LOGO_ERROR';

export const GET_ALL_DOCKS_PENDING = 'GET_ALL_DOCKS_PENDING';
export const GET_ALL_DOCKS_SUCCESS = 'GET_ALL_DOCKS_SUCCESS';
export const GET_ALL_DOCKS_SUCCESS_BUT_NULL = 'GET_ALL_DOCKS_SUCCESS_BUT_NULL';
export const GET_ALL_DOCKS_ERROR = 'GET_ALL_DOCKS_ERROR';

export const SET_SELECTED_DOCK = 'SET_SELECTED_DOCK';
export const RESET_DOCK_STATE = 'RESET_DOCK_STATE';

export const SET_SELECTED_DOCK_ALLOWED_WORKFLOWS =
  'SET_SELECTED_DOCK_ALLOWED_WORKFLOWS';
export const RESET_DOCK_ALLOWED_WORKFLOWS_STATE =
  'RESET_DOCK_ALLOWED_WORKFLOWS_STATE';

export const UPDATE_HDC_SELECTIONS = 'UPDATE_HDC_SELECTIONS';

export const HDC_VALIDATE_USER_BY_CELL_PHONE_IDLE =
  'HDC_VALIDATE_USER_BY_CELL_PHONE_IDLE';
export const HDC_VALIDATE_USER_BY_CELL_PHONE_PENDING =
  'HDC_VALIDATE_USER_BY_CELL_PHONE_PENDING';
export const HDC_VALIDATE_USER_BY_CELL_PHONE_SUCCESS =
  'HDC_VALIDATE_USER_BY_CELL_PHONE_SUCCESS';
export const HDC_VALIDATE_USER_BY_CELL_PHONE_ERROR =
  'HDC_VALIDATE_USER_BY_CELL_PHONE_ERROR';

export const ADD_NEW_CARRIER_COMPANY_PENDING =
  'ADD_NEW_CARRIER_COMPANY_PENDING';
export const ADD_NEW_CARRIER_COMPANY_SUCCESS =
  'ADD_NEW_CARRIER_COMPANY_SUCCESS';
export const ADD_NEW_CARRIER_COMPANY_ERROR = 'ADD_NEW_CARRIER_COMPANY_ERROR';

export const HDC_UPDATE_NEW_USER_PAYLOAD_IDLE = 'HDC_UPDATE_NEW_USER_PAYLOAD_IDLE';
export const HDC_UPDATE_NEW_USER_PAYLOAD = 'HDC_UPDATE_NEW_USER_PAYLOAD';

export const ADD_UPDATE_USER_PENDING = 'ADD_UPDATE_USER_PENDING';
export const ADD_UPDATE_USER_SUCCESS = 'ADD_UPDATE_USER_SUCCESS';
export const ADD_UPDATE_USER_ERROR = 'ADD_UPDATE_USER_ERROR';

export const VISITOR_GENERATE_OTP = 'VISITOR_GENERATE_OTP';
export const VISITOR_GENERATE_OTP_SUCCESS = 'VISITOR_GENERATE_OTP_SUCCESS';
export const VISITOR_GENERATE_OTP_ERROR = 'VISITOR_GENERATE_OTP_ERROR';

export const VISITOR_VERIFY_OTP = 'VISITOR_VERIFY_OTP';
export const VISITOR_VERIFY_OTP_SUCCESS = 'VISITOR_VERIFY_OTP_SUCCESS';
export const VISITOR_VERIFY_OTP_ERROR = 'VISITOR_VERIFY_OTP_ERROR';

export const CHECK_LOAD_TYPE_IDLE = 'CHECK_LOAD_TYPE_IDLE';
export const CHECK_LOAD_TYPE_PENDING = 'CHECK_LOAD_TYPE_PENDING';
export const CHECK_LOAD_TYPE_SUCCESS = 'CHECK_LOAD_TYPE_SUCCESS';
export const CHECK_LOAD_TYPE_ERROR = 'CHECK_LOAD_TYPE_ERROR';

export const GET_AWS_LANGUAGES_LOOKUPS_IDLE = 'GET_AWS_LANGUAGES_LOOKUPS_IDLE';
export const GET_AWS_LANGUAGES_LOOKUPS = 'GET_AWS_LANGUAGES_LOOKUPS';
export const GET_AWS_LANGUAGES_LOOKUPS_SUCCESS =
  'GET_AWS_LANGUAGES_LOOKUPS_SUCCESS';
export const GET_AWS_LANGUAGES_LOOKUPS_ERROR =
  'GET_AWS_LANGUAGES_LOOKUPS_ERROR';

export const TRANSLATE_MSGS = 'TRANSLATE_MSGS';
export const TRANSLATE_MSGS_SUCCESS = 'TRANSLATE_MSGS_SUCCESS';
export const TRANSLATE_MSGS_ERROR = 'TRANSLATE_MSGS_ERROR';

export const GET_LOAD_TYPE_LOOKUPS = 'GET_LOAD_TYPE_LOOKUPS';
export const GET_LOAD_TYPE_LOOKUPS_SUCCESS = 'GET_LOAD_TYPE_LOOKUPS_SUCCESS';
export const GET_LOAD_TYPE_LOOKUPS_ERROR = 'GET_LOAD_TYPE_LOOKUPS_ERROR';

export const APP_HEART_BEAT_API_IDLE = 'APP_HEART_BEAT_API_IDLE';
export const APP_HEART_BEAT_API_PENDING = 'APP_HEART_BEAT_API_PENDING';
export const APP_HEART_BEAT_API_SUCCESS = 'APP_HEART_BEAT_API_SUCCESS';
export const APP_HEART_BEAT_API_ERROR = 'APP_HEART_BEAT_API_ERROR';
