export const SET_APP_STATE = 'SET_APP_STATE';

export const APP_IDLE = 'APP_IDLE';

export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const FILTERED_SCREEN_SELECTED = 'FILTERED_SCREEN_SELECTED';

export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
